apiVersion: v1
kind: Service
metadata:
  name: end-user-service-frontend
  namespace: quote-of-the-day-app
spec:
  type: NodePort
  selector:
    app: end-user-service-frontend
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    nodePort: 32000 
