apiVersion: v1
kind: Service
metadata:
  name: quote-mysql
  namespace: quote-of-the-day-app  # Specify the namespace here
spec:
  selector:
    app: quote-service-backend
  ports:
  - port: 3306
    targetPort: 3306
