apiVersion: v1
kind: Service
metadata:
  name: quote-app
  namespace: quote-of-the-day-app  # Specify the namespace here
spec:
  selector:
    app: quote-service-frontend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
