apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
  namespace: quote-of-the-day-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service-frontend
  template:
    metadata:
      labels:
        app: quote-service-frontend
    spec:
      containers:
      - name: quote-app
        image: hayder89/quote-service:latest
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret 
              key: userpassword
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        - name: DATABASE_URI
          value: mysql://admin:$(MYSQL_USER_PASSWORD)@quote-mysql:3306/quotesdb
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672/"
        ports:
        - containerPort: 5000
