apiVersion: v1
kind: Service
metadata:
  name: admin-service-frontend
  namespace: quote-of-the-day-app
spec:
  type: NodePort
  selector:
    app: admin-service-frontend
  ports:
  - port: 5003  # Assuming 5003 is the port for the admin service
    targetPort: 5003
    protocol: TCP
    nodePort: 30003  # Make sure this port isn't already in use
