apiVersion: v1
kind: Service
metadata:
  name: analytics-app
  namespace: quote-of-the-day-app  # Specify the namespace here
spec:
  selector:
    app: analytics-service
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
