# mysql-service.yaml for analytics-service
apiVersion: v1
kind: Service
metadata:
  name: analytics-mysql
  namespace: quote-of-the-day-app
spec:
  ports:
  - port: 3306
  selector:
    app: analytics-service-backend
