# mysql-persistent-volume.yaml for analytics-service
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
