apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  namespace: quote-of-the-day-app  # Specify the namespace here
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/rabbitmq
