apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: quote-of-the-day-app
spec:
  selector:
    app: rabbitmq-service
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management
